// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.6.1
// source: zigbee-service/zigbee-service.proto

package zigbee_service_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZigbeeServiceClient is the client API for ZigbeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZigbeeServiceClient interface {
	GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDevicesResponse, error)
	SetDeviceState(ctx context.Context, in *SetDeviceStateRequest, opts ...grpc.CallOption) (*SetDeviceStateResponse, error)
}

type zigbeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZigbeeServiceClient(cc grpc.ClientConnInterface) ZigbeeServiceClient {
	return &zigbeeServiceClient{cc}
}

func (c *zigbeeServiceClient) GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDevicesResponse, error) {
	out := new(GetDevicesResponse)
	err := c.cc.Invoke(ctx, "/zigbee_service.ZigbeeService/GetDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zigbeeServiceClient) SetDeviceState(ctx context.Context, in *SetDeviceStateRequest, opts ...grpc.CallOption) (*SetDeviceStateResponse, error) {
	out := new(SetDeviceStateResponse)
	err := c.cc.Invoke(ctx, "/zigbee_service.ZigbeeService/SetDeviceState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZigbeeServiceServer is the server API for ZigbeeService service.
// All implementations must embed UnimplementedZigbeeServiceServer
// for forward compatibility
type ZigbeeServiceServer interface {
	GetDevices(context.Context, *Empty) (*GetDevicesResponse, error)
	SetDeviceState(context.Context, *SetDeviceStateRequest) (*SetDeviceStateResponse, error)
	mustEmbedUnimplementedZigbeeServiceServer()
}

// UnimplementedZigbeeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedZigbeeServiceServer struct {
}

func (UnimplementedZigbeeServiceServer) GetDevices(context.Context, *Empty) (*GetDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedZigbeeServiceServer) SetDeviceState(context.Context, *SetDeviceStateRequest) (*SetDeviceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceState not implemented")
}
func (UnimplementedZigbeeServiceServer) mustEmbedUnimplementedZigbeeServiceServer() {}

// UnsafeZigbeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZigbeeServiceServer will
// result in compilation errors.
type UnsafeZigbeeServiceServer interface {
	mustEmbedUnimplementedZigbeeServiceServer()
}

func RegisterZigbeeServiceServer(s grpc.ServiceRegistrar, srv ZigbeeServiceServer) {
	s.RegisterService(&ZigbeeService_ServiceDesc, srv)
}

func _ZigbeeService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZigbeeServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbee_service.ZigbeeService/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZigbeeServiceServer).GetDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZigbeeService_SetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZigbeeServiceServer).SetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zigbee_service.ZigbeeService/SetDeviceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZigbeeServiceServer).SetDeviceState(ctx, req.(*SetDeviceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZigbeeService_ServiceDesc is the grpc.ServiceDesc for ZigbeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZigbeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zigbee_service.ZigbeeService",
	HandlerType: (*ZigbeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _ZigbeeService_GetDevices_Handler,
		},
		{
			MethodName: "SetDeviceState",
			Handler:    _ZigbeeService_SetDeviceState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zigbee-service/zigbee-service.proto",
}
