// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: zigbee-service/zigbee-service.proto

package zigbee_service_pb

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State_Type int32

const (
	State_Type_UNKNOWN State_Type = 0
	State_Type_BOOLEAN State_Type = 1
	State_Type_NUMBER  State_Type = 2
	State_Type_TEXT    State_Type = 3
)

// Enum value maps for State_Type.
var (
	State_Type_name = map[int32]string{
		0: "Type_UNKNOWN",
		1: "Type_BOOLEAN",
		2: "Type_NUMBER",
		3: "Type_TEXT",
	}
	State_Type_value = map[string]int32{
		"Type_UNKNOWN": 0,
		"Type_BOOLEAN": 1,
		"Type_NUMBER":  2,
		"Type_TEXT":    3,
	}
)

func (x State_Type) Enum() *State_Type {
	p := new(State_Type)
	*p = x
	return p
}

func (x State_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_zigbee_service_zigbee_service_proto_enumTypes[0].Descriptor()
}

func (State_Type) Type() protoreflect.EnumType {
	return &file_zigbee_service_zigbee_service_proto_enumTypes[0]
}

func (x State_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State_Type.Descriptor instead.
func (State_Type) EnumDescriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{2, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{0}
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Reachable       *wrappers.BoolValue     `protobuf:"bytes,3,opt,name=reachable,proto3" json:"reachable,omitempty"`
	Characteristics *Device_Characteristics `protobuf:"bytes,4,opt,name=characteristics,proto3" json:"characteristics,omitempty"`
	InitialStates   []*State                `protobuf:"bytes,5,rep,name=initial_states,json=initialStates,proto3" json:"initial_states,omitempty"`
	Readable        []*State                `protobuf:"bytes,6,rep,name=readable,proto3" json:"readable,omitempty"`
	Editable        []*State                `protobuf:"bytes,7,rep,name=editable,proto3" json:"editable,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetReachable() *wrappers.BoolValue {
	if x != nil {
		return x.Reachable
	}
	return nil
}

func (x *Device) GetCharacteristics() *Device_Characteristics {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

func (x *Device) GetInitialStates() []*State {
	if x != nil {
		return x.InitialStates
	}
	return nil
}

func (x *Device) GetReadable() []*State {
	if x != nil {
		return x.Readable
	}
	return nil
}

func (x *Device) GetEditable() []*State {
	if x != nil {
		return x.Editable
	}
	return nil
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type State_Type `protobuf:"varint,1,opt,name=type,proto3,enum=zigbee_service.State_Type" json:"type,omitempty"`
	Name string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//	*State_BooleanValue
	//	*State_NumberValue
	//	*State_TextValue
	//	*State_FloatValue
	Value isState_Value `protobuf_oneof:"value"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetType() State_Type {
	if x != nil {
		return x.Type
	}
	return State_Type_UNKNOWN
}

func (x *State) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *State) GetValue() isState_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *State) GetBooleanValue() *wrappers.BoolValue {
	if x, ok := x.GetValue().(*State_BooleanValue); ok {
		return x.BooleanValue
	}
	return nil
}

func (x *State) GetNumberValue() *wrappers.Int64Value {
	if x, ok := x.GetValue().(*State_NumberValue); ok {
		return x.NumberValue
	}
	return nil
}

func (x *State) GetTextValue() *wrappers.StringValue {
	if x, ok := x.GetValue().(*State_TextValue); ok {
		return x.TextValue
	}
	return nil
}

func (x *State) GetFloatValue() *wrappers.FloatValue {
	if x, ok := x.GetValue().(*State_FloatValue); ok {
		return x.FloatValue
	}
	return nil
}

type isState_Value interface {
	isState_Value()
}

type State_BooleanValue struct {
	BooleanValue *wrappers.BoolValue `protobuf:"bytes,3,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type State_NumberValue struct {
	NumberValue *wrappers.Int64Value `protobuf:"bytes,4,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type State_TextValue struct {
	TextValue *wrappers.StringValue `protobuf:"bytes,5,opt,name=text_value,json=textValue,proto3,oneof"`
}

type State_FloatValue struct {
	FloatValue *wrappers.FloatValue `protobuf:"bytes,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

func (*State_BooleanValue) isState_Value() {}

func (*State_NumberValue) isState_Value() {}

func (*State_TextValue) isState_Value() {}

func (*State_FloatValue) isState_Value() {}

type GetDevicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SetDeviceStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	States []*State `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
}

func (x *SetDeviceStateRequest) Reset() {
	*x = SetDeviceStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeviceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceStateRequest) ProtoMessage() {}

func (x *SetDeviceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceStateRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceStateRequest) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetDeviceStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetDeviceStateRequest) GetStates() []*State {
	if x != nil {
		return x.States
	}
	return nil
}

type SetDeviceStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	States []*State `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
}

func (x *SetDeviceStateResponse) Reset() {
	*x = SetDeviceStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceStateResponse) ProtoMessage() {}

func (x *SetDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{5}
}

func (x *SetDeviceStateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetDeviceStateResponse) GetStates() []*State {
	if x != nil {
		return x.States
	}
	return nil
}

type Device_Characteristics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string                           `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Vendor      string                           `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model       string                           `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Actions     []*Device_Characteristics_Action `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *Device_Characteristics) Reset() {
	*x = Device_Characteristics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device_Characteristics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device_Characteristics) ProtoMessage() {}

func (x *Device_Characteristics) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device_Characteristics.ProtoReflect.Descriptor instead.
func (*Device_Characteristics) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Device_Characteristics) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Device_Characteristics) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Device_Characteristics) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device_Characteristics) GetActions() []*Device_Characteristics_Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Device_Characteristics_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Device_Characteristics_Action) Reset() {
	*x = Device_Characteristics_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zigbee_service_zigbee_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device_Characteristics_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device_Characteristics_Action) ProtoMessage() {}

func (x *Device_Characteristics_Action) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_service_zigbee_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device_Characteristics_Action.ProtoReflect.Descriptor instead.
func (*Device_Characteristics_Action) Descriptor() ([]byte, []int) {
	return file_zigbee_service_zigbee_service_proto_rawDescGZIP(), []int{1, 0, 0}
}

var File_zigbee_service_zigbee_service_proto protoreflect.FileDescriptor

var file_zigbee_service_zigbee_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x93, 0x04, 0x0a,
	0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x72,
	0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63,
	0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x3c, 0x0a, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x64, 0x69, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x7a, 0x69, 0x67,
	0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x08, 0x65, 0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0xb4, 0x01, 0x0a, 0x0f,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x47, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x08, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xa4, 0x03, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x7a, 0x69, 0x67,
	0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x41, 0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x36,
	0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x74, 0x65, 0x78, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x4a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10, 0x03,
	0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x22, 0x5a, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x22, 0x5b, 0x0a,
	0x16, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x7a, 0x69,
	0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x32, 0xf4, 0x01, 0x0a, 0x0d, 0x5a,
	0x69, 0x67, 0x62, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x7a, 0x69, 0x67,
	0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x22, 0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x80,
	0x01, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x25, 0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x7a, 0x69, 0x67, 0x62, 0x65,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65,
	0x74, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x3a, 0x01,
	0x2a, 0x42, 0x23, 0x5a, 0x21, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x3b, 0x7a, 0x69, 0x67, 0x62, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zigbee_service_zigbee_service_proto_rawDescOnce sync.Once
	file_zigbee_service_zigbee_service_proto_rawDescData = file_zigbee_service_zigbee_service_proto_rawDesc
)

func file_zigbee_service_zigbee_service_proto_rawDescGZIP() []byte {
	file_zigbee_service_zigbee_service_proto_rawDescOnce.Do(func() {
		file_zigbee_service_zigbee_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_zigbee_service_zigbee_service_proto_rawDescData)
	})
	return file_zigbee_service_zigbee_service_proto_rawDescData
}

var file_zigbee_service_zigbee_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zigbee_service_zigbee_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zigbee_service_zigbee_service_proto_goTypes = []interface{}{
	(State_Type)(0),                       // 0: zigbee_service.State.Type
	(*Empty)(nil),                         // 1: zigbee_service.Empty
	(*Device)(nil),                        // 2: zigbee_service.Device
	(*State)(nil),                         // 3: zigbee_service.State
	(*GetDevicesResponse)(nil),            // 4: zigbee_service.GetDevicesResponse
	(*SetDeviceStateRequest)(nil),         // 5: zigbee_service.SetDeviceStateRequest
	(*SetDeviceStateResponse)(nil),        // 6: zigbee_service.SetDeviceStateResponse
	(*Device_Characteristics)(nil),        // 7: zigbee_service.Device.Characteristics
	(*Device_Characteristics_Action)(nil), // 8: zigbee_service.Device.Characteristics.Action
	(*wrappers.BoolValue)(nil),            // 9: google.protobuf.BoolValue
	(*wrappers.Int64Value)(nil),           // 10: google.protobuf.Int64Value
	(*wrappers.StringValue)(nil),          // 11: google.protobuf.StringValue
	(*wrappers.FloatValue)(nil),           // 12: google.protobuf.FloatValue
}
var file_zigbee_service_zigbee_service_proto_depIdxs = []int32{
	9,  // 0: zigbee_service.Device.reachable:type_name -> google.protobuf.BoolValue
	7,  // 1: zigbee_service.Device.characteristics:type_name -> zigbee_service.Device.Characteristics
	3,  // 2: zigbee_service.Device.initial_states:type_name -> zigbee_service.State
	3,  // 3: zigbee_service.Device.readable:type_name -> zigbee_service.State
	3,  // 4: zigbee_service.Device.editable:type_name -> zigbee_service.State
	0,  // 5: zigbee_service.State.type:type_name -> zigbee_service.State.Type
	9,  // 6: zigbee_service.State.boolean_value:type_name -> google.protobuf.BoolValue
	10, // 7: zigbee_service.State.number_value:type_name -> google.protobuf.Int64Value
	11, // 8: zigbee_service.State.text_value:type_name -> google.protobuf.StringValue
	12, // 9: zigbee_service.State.float_value:type_name -> google.protobuf.FloatValue
	2,  // 10: zigbee_service.GetDevicesResponse.devices:type_name -> zigbee_service.Device
	3,  // 11: zigbee_service.SetDeviceStateRequest.states:type_name -> zigbee_service.State
	3,  // 12: zigbee_service.SetDeviceStateResponse.states:type_name -> zigbee_service.State
	8,  // 13: zigbee_service.Device.Characteristics.actions:type_name -> zigbee_service.Device.Characteristics.Action
	1,  // 14: zigbee_service.ZigbeeService.GetDevices:input_type -> zigbee_service.Empty
	5,  // 15: zigbee_service.ZigbeeService.SetDeviceState:input_type -> zigbee_service.SetDeviceStateRequest
	4,  // 16: zigbee_service.ZigbeeService.GetDevices:output_type -> zigbee_service.GetDevicesResponse
	6,  // 17: zigbee_service.ZigbeeService.SetDeviceState:output_type -> zigbee_service.SetDeviceStateResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_zigbee_service_zigbee_service_proto_init() }
func file_zigbee_service_zigbee_service_proto_init() {
	if File_zigbee_service_zigbee_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zigbee_service_zigbee_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigbee_service_zigbee_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigbee_service_zigbee_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigbee_service_zigbee_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigbee_service_zigbee_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeviceStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigbee_service_zigbee_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeviceStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigbee_service_zigbee_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device_Characteristics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zigbee_service_zigbee_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device_Characteristics_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_zigbee_service_zigbee_service_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*State_BooleanValue)(nil),
		(*State_NumberValue)(nil),
		(*State_TextValue)(nil),
		(*State_FloatValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zigbee_service_zigbee_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zigbee_service_zigbee_service_proto_goTypes,
		DependencyIndexes: file_zigbee_service_zigbee_service_proto_depIdxs,
		EnumInfos:         file_zigbee_service_zigbee_service_proto_enumTypes,
		MessageInfos:      file_zigbee_service_zigbee_service_proto_msgTypes,
	}.Build()
	File_zigbee_service_zigbee_service_proto = out.File
	file_zigbee_service_zigbee_service_proto_rawDesc = nil
	file_zigbee_service_zigbee_service_proto_goTypes = nil
	file_zigbee_service_zigbee_service_proto_depIdxs = nil
}
